#!/bin/sh

set -eux

rm -rf .venv
python3.11 -m venv .venv
. .venv/bin/activate
python -m pip install -U pip setuptools wheel
pip install -r requirements.txt
./program.py
pip install -r requirements-dev.txt
flake8 program.py
pylint program.py
mypy program.py
pyright program.py
printf 'Everything looks good!\n'
